version: '3.5'

services:
  database:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
